name: Unit Test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build

  deploy:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: use-vue
      USE_VUE_TOKEN: ${{ secrets.USE_VUE_TOKEN }}
      USER_NAME: fegg
      USER_EMAIL: lulin666000@gmail.com
      PUBLIC_DIR_DOC: ./docs/dist

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build

      - name: Publish docs
        run: |
          echo $USE_VUE_TOKEN
          echo $GITHUB_TOKEN
          echo $USER_NAME
          echo $USER_EMAIL
          echo $GITHUB_REPOSITORY
          pnpm docs-build
          cd $PUBLIC_DIR_DOC
          git init
          git config --local user.name $USER_NAME
          git config --local user.email $USER_EMAIL
          git status
          git remote add origin https://$USE_VUE_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy to Github pages"
          git push origin gh-pages
          echo 🤘 deploy gh-pages complete.
