name: Unit Test

on: [ push, pull_request ]

jobs:
  test:
    env:
      ACCESS_TOKEN: ${{secrets.use_vue_token}}
      USER_NAME: fegg
      USER_EMAIL: lulin666000@gmail.com

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Publish docs
        with:
          github_token: $ACCESS_TOKEN
          publish_dir: ./docs/dist
        run: |
          git config --local user.name $USER_NAME
          git config --local user.email $USER_EMAIL
          pnpm docs-build-deploy
          echo 🤘 deploy gh-pages complete.
